from src.database import *
clear_errors()
print("Успешно очищены ошибки")
